service: covid-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  stackName: myserverless-lambda-${self:provider.stage}
  role: arn:aws:iam::515110458415:role/lambda-apigateway-role

functions:
  readCsv:
    handler: handler.readCsv
    name: ${self:provider.stage}-mylambda
    events:
      - http:
          path: /
          method: any
          cors: true
          private: false

