service: covid-api

package:
  exclude:
    - secrets.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    MAIL_ACCESS: "${self:custom.secrets.MAIL_ACCESS}"

functions:
  covidApi:
    handler: handler.covidApi
    name: ${self:provider.stage}-covidApi-lambda
    events:
      - http:
          path: send-mail
          method: post
          cors: true
          private: false
          request:
            parameters:
              headers:
                - "Accept"
                - "Content-Type"
